FROM ubuntu:20.04


RUN set -x && \
    . /usr/share/lmod/lmod/init/sh && \
    eb --robot Bowtie2-2.4.1-GCC-9.3.0.eb SAMtools-1.10-GCC-9.3.0.eb --installpath=/app/ --prefix=/scratch --tmpdir=/scratch/tmp

RUN touch ${HOME}/.bashrc && \
    echo '' >> ${HOME}/.bashrc && \
    echo '# Added by easybuild docker packaging' >> ${HOME}/.bashrc && \
    echo 'source /usr/share/lmod/lmod/init/bash' >> ${HOME}/.bashrc && \
    echo 'module use /app/modules/all' >> ${HOME}/.bashrc && \
    echo 'module load Bowtie2/2.4.1-GCC-9.3.0 SAMtools/1.10-GCC-9.3.0' >> ${HOME}/.bashrc

CMD ["/bin/bash", "-l"]