{{- if .Values.cronJobs}}
  {{- range $cronJobsIndex, $cronJob := $.Values.cronJobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ $.Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{$.Release.Service | quote }}
    app.kubernetes.io/instance: {{$.Release.Name | quote }}
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
{{- if $cronJob.annotations }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    {{- toYaml $cronJob.annotations | nindent 4 }}
{{- end }}
spec:
  schedule: {{ $cronJob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: "{{ $.Release.Name }}"
          labels:
            app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
            app.kubernetes.io/instance: {{ $.Release.Name | quote }}
            helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
        spec:
          restartPolicy: {{ $cronJob.restartPolicy | default "Never" | quote }}
          containers:
            - name: {{ $cronJob.name }}
        {{- if $cronJob.image }}
              image: {{ $cronJob.image | quote }}
        {{- else }}
        {{- with index $.Values.containers 0 }}
              image: {{ .image | quote }}
        {{- end }}
        {{- end }}
              command: {{- toYaml $cronJob.command | nindent 16 }}
              args: {{- toYaml $cronJob.args | nindent 16 }}
        {{- if $cronJob.env }}
              env: {{- toYaml $cronJob.env | nindent 16 }}
        {{- end }}
        {{- if $cronJob.envFrom }}
              envFrom: {{- toYaml $cronJob.envFrom | nindent 16 }}
        {{- end }}
              volumeMounts:
                {{- range $volumeMountIndex, $volumeMount := $cronJob.volumeMounts }}
                - mountPath: {{ $volumeMount.containerPath | quote }}
                  name: {{ $volumeMount.volume.name | quote }}
                  {{- if $volumeMount.volume.subPath }}
                  subPath: {{ trimAll "/" $volumeMount.volume.subPath | default "" | quote }}
                  {{- end }}
                  readOnly: {{ $volumeMount.volume.readOnly | default false }}
                {{- end }}
          volumes:
            {{- range $volumeIndex, $volume := $.Values.volumes }}
            {{- $isVolumeOfThisComponent := false }}
            {{- range $cronJobIndex, $cronJob := $.Values.cronJobs }}
              {{- range $volumeMountIndex, $volumeMount := $cronJob.volumeMounts }}
                {{- if or $volumeMount.volume.readOnly $volumeMount.volume.shared $volume.secret $volume.configMap $volume.hostPath (hasKey $volume "emptyDir") }}
                  {{- if eq $volume.name $volumeMount.volume.name }}
                    {{- $isVolumeOfThisComponent = true }}
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
            {{- if $isVolumeOfThisComponent }}
            - name: {{ $volume.name | quote }}
              {{- if $volume.secret }}
              secret:
                {{ toYaml $volume.secret | indent 12 }}
              {{- else }}
              {{- if $volume.configMap }}
              configMap:
                {{ toYaml $volume.configMap | indent 12 }}
              {{- else }}
              {{- if $volume.hostPath }}
              hostPath:
                {{ toYaml $volume.hostPath | indent 12 }}
              {{- else }}
              {{- if hasKey $volume "emptyDir" }}
              emptyDir:
                {{ toYaml $volume.emptyDir | indent 12 }}
              {{- else }}
              persistentVolumeClaim:
                claimName: {{ $volume.name | quote }}
              {{- end }}
              {{- end }}
              {{- end }}
              {{- end }}
            {{- end }}
            {{- end }}
{{- if $cronJob.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ $cronJob.ttlSecondsAfterFinished }}
{{- end }}
---
      {{- end }}
      {{- end }}
