{{- if .Values.cronJobs}}
  {{- range $cronJobs, $job := $.Values.cronJobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ $.Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{$.Release.Service | quote }}
    app.kubernetes.io/instance: {{$.Release.Name | quote }}
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    {{- toYaml $job.annotations | nindent 4 }}
spec:
  schedule: {{ $job.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: "{{ $.Release.Name }}"
          labels:
            app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
            app.kubernetes.io/instance: {{ $.Release.Name | quote }}
            helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
        spec:
          restartPolicy: Never
          containers:
            - name: {{ $job.name }}
        {{- if $job.image }}
              image: {{ $job.image | quote }}
        {{- else }}
        {{- with index $.Values.containers 0 }}
              image: {{ .image | quote }}
        {{- end }}
        {{- end }}
              command: {{- toYaml $job.command | nindent 16 }}
              args: {{- toYaml $job.args | nindent 16 }}
              env:
      {{- toYaml $job.env | nindent 16 }}
              envFrom:
      {{- toYaml $job.envFrom | nindent 16 }}
{{- if $job.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ $job.ttlSecondsAfterFinished }}
{{- end }}
---
      {{- end }}
      {{- end }}
