{{- if $.Values.hydra }} 
{{- range $hydraClientIndex, $hydraClient := $.Values.hydra.clients }}
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: {{ $hydraClient.name }}
  {{- if $hydraClient.namespace }}
  namespace: {{ $hydraClient.namespace }}
  {{- end }}
  labels:
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
{{ toYaml $hydraClient.client | indent 4 }}
---
{{- end }}
{{- end }}
