{{- if .Values.initJobs }}
{{- range $initJobs, $job := $.Values.initJobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ $.Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    "tags.datadoghq.com/service": {{ $.Release.Name | quote }}
    "tags.datadoghq.com/version": "{{ $.Values.Version }}"
  annotations:
    {{- if $job.annotations }}
    {{- range $key, $value := $job.annotations }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
spec:
  template:
    metadata:
      name: "{{ $.Release.Name }}-{{ $job.name }}"
      labels:
        app.kubernetes.io/name: {{ $.Release.Name | quote }}
        app.kubernetes.io/component: {{ $.Release.Name | quote }}
        app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
        app.kubernetes.io/instance: {{$.Release.Name | quote }}
        helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
        "tags.datadoghq.com/service": {{ $.Release.Name | quote }}
        "tags.datadoghq.com/version": "{{ $.Values.Version }}"
    spec:
      shareProcessNamespace: {{ $job.shareProcessNamespace | default false }}
      serviceAccountName: {{ if $.Values.serviceAccount }}{{ if kindIs "map" $.Values.serviceAccount }}{{ $.Values.serviceAccount.name }}{{ else }}{{ $.Values.serviceAccount }}{{ end }}{{ else }}default{{ end }}
      {{- if $job.podSecurityContext }}
      securityContext: {{ toYaml $job.podSecurityContext | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      imagePullSecrets:
        {{- range $secretIndex, $secretName := $.Values.pullSecrets }}
        - name: {{ $secretName | quote }}
        {{- end }}
      {{- if $job.initContainers }}
      initContainers:
        {{- range $containerIndex, $initContainer := $job.initContainers }}
        {{- $tag := default $.Values.imageTag $initContainer.imageTag }}
        {{- $sha := default $.Values.imageSha $initContainer.imageSha }}
        - name: {{ $initContainer.name }}
          image: {{ if $tag }}{{ printf "%s:%s" $initContainer.image $tag | quote }}{{ else if $sha }}{{ printf "%s@%s" $initContainer.image $sha | quote }}{{ else }}{{ $initContainer.image | quote }}{{ end }}
          {{- if $initContainer.imagePullPolicy}}
          imagePullPolicy: {{ $initContainer.imagePullPolicy }}
          {{- end }}
          restartPolicy: {{ $initContainer.restartPolicy | default "Never" }}
          {{- if $initContainer.workingDir }}
          workingDir: {{ $initContainer.workingDir }}
          {{- end }}
          {{- if $initContainer.command }}
          command: {{- toYaml $initContainer.command | nindent 12 }}
          {{- end }}
          {{- if $initContainer.args }}
          args: {{- toYaml $initContainer.args | nindent 12 }}
          {{- end }}
          {{- if $initContainer.env }}
          env: {{- toYaml $initContainer.env | nindent 12 }}
          {{- end }}
          {{- if $initContainer.envFrom }}
          envFrom: {{- toYaml $initContainer.envFrom | nindent 12 }}
          {{- end }}
          {{- if $initContainer.volumeMounts }}
          volumeMounts:
            {{- range $volumeMountIndex, $volumeMount := $initContainer.volumeMounts }}
            - mountPath: {{ $volumeMount.containerPath | quote }}
              name: {{ $volumeMount.volume.name | quote }}
              {{- if $volumeMount.volume.subPath }}
              subPath: {{ trimAll "/" $volumeMount.volume.subPath | default "" | quote }}
              {{- end }}
              readOnly: {{ $volumeMount.volume.readOnly | default false }}
            {{- end }}
          {{- end }}
          {{- if $initContainer.resources }}
          resources: {{- toYaml $initContainer.resources | nindent 12 }}
          {{- else }}
          resources:
            limits:
              cpu: 400m
              memory: 250Mi
            requests:
              cpu: 10m
              memory: 50Mi
          {{- end }}
        {{- end }}
      {{- end }}
      containers:
        {{- range $containerIndex, $jobContainer := $job.containers }}
        {{- $tag := default $.Values.imageTag $jobContainer.imageTag }}
        {{- $sha := default $.Values.imageSha $jobContainer.imageSha }}
        - name: {{ $jobContainer.name }}
          image: {{ if $tag }}{{ printf "%s:%s" $jobContainer.image $tag | quote }}{{ else if $sha }}{{ printf "%s@%s" $jobContainer.image $sha | quote }}{{ else }}{{ $jobContainer.image | quote }}{{ end }}
          {{- if $jobContainer.imagePullPolicy}}
          imagePullPolicy: {{ $jobContainer.imagePullPolicy }}
          {{- end }}
          {{- if $jobContainer.workingDir }}
          workingDir: {{ $jobContainer.workingDir }}
          {{- end }}
          {{- if $jobContainer.command }}
          command: {{- toYaml $jobContainer.command | nindent 12 }}
          {{- end }}
          {{- if $jobContainer.args }}
          args: {{- toYaml $jobContainer.args | nindent 12 }}
          {{- end }}
          env:
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            {{- if $jobContainer.env }}
            {{- toYaml $jobContainer.env | nindent 12 }}
            {{- end }}
          {{- if $jobContainer.envFrom }}
          envFrom: {{- toYaml $jobContainer.envFrom | nindent 12 }}
          {{- end }}
          {{- if $jobContainer.volumeMounts }}
          volumeMounts:
            {{- range $volumeMountIndex, $volumeMount := $jobContainer.volumeMounts }}
            - mountPath: {{ $volumeMount.containerPath | quote }}
              name: {{ $volumeMount.volume.name | quote }}
              {{- if $volumeMount.volume.subPath }}
              subPath: {{ trimAll "/" $volumeMount.volume.subPath | default "" | quote }}
              {{- end }}
              readOnly: {{ $volumeMount.volume.readOnly | default false }}
            {{- end }}
          {{- end }}
          {{- if $jobContainer.resources }}
          resources: {{- toYaml $jobContainer.resources | nindent 12 }}
          {{- else }}
          resources:
            limits:
              cpu: 400m
              memory: 250Mi
            requests:
              cpu: 10m
              memory: 50Mi
          {{- end }}
        {{- end }}
      {{- if $job.volumes }}
      volumes:
        {{- range $volumeIndex, $volume := $job.volumes }}
        - name: {{ $volume.name | quote }}
          {{- if $volume.secret }}
          secret: {{- toYaml $volume.secret | nindent 12 }}
          {{- else if $volume.configMap }}
          configMap: {{- toYaml $volume.configMap | nindent 12 }}
          {{- else if $volume.hostPath }}
          hostPath: {{- toYaml $volume.hostPath | nindent 12 }}
          {{- else if hasKey $volume "emptyDir" }}
          emptyDir: {{- toYaml $volume.emptyDir | nindent 12 }}
          {{- else if hasKey $volume "csi" }}
          csi: {{- toYaml $volume.csi | nindent 12 }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ $volume.name | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
---
{{- end }}
{{- end }}