{{- if .Values.podDisruptionBudget -}}
{{- $kind := "Deployment" }}
{{- range $containerIndex, $container := $.Values.containers }}
  {{- range $volumeMountIndex, $volumeMount := $container.volumeMounts }}
    {{- if $volumeMount.volume.readOnly }}
    {{- else }}
      {{- range $volumeIndex, $volume := $.Values.volumes }}
        {{- if eq $volumeMount.volume.name $volume.name }}
          {{- $kind = "StatefulSet" }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $.Release.Name | quote }}
  labels:
    "app.kubernetes.io/name": "anivive-pdb-{{ $.Release.Name  }}"
    "app.kubernetes.io/component": {{ $.Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
    {{- range $labelName, $labelValue := $.Values.labels }}
    {{ $labelName | quote }}: {{ $labelValue | quote }}
    {{- end }}
  annotations:
    "helm.sh/chart": "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    {{- range $annotationName, $annotationValue := $.Values.annotations }}
    {{ $annotationName | quote }}: {{ $annotationValue | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      "app.kubernetes.io/component": {{ $.Release.Name | quote }}
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
{{- end -}}