{{- if $.Values.autoScaling}}
{{- if $.Values.autoScaling.horizontal }}
{{- if gt $.Values.autoScaling.horizontal.maxReplicas $.Values.replicas }}
{{- $kind := "Deployment" }}
{{- range $containerIndex, $container := $.Values.containers }}
  {{- range $volumeMountIndex, $volumeMount := $container.volumeMounts }}
    {{- if $volumeMount.volume.readOnly }}
    {{- else }}
      {{- range $volumeIndex, $volume := $.Values.volumes }}
        {{- if eq $volumeMount.volume.name $volume.name }}
          {{- $kind = "StatefulSet" }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Release.Name | quote }}
  labels:
    "app.kubernetes.io/name": "anivive-Autoscaler"
    "app.kubernetes.io/component": {{ $.Release.Name | quote }}
    "app.kubernetes.io/managed-by": {{ $.Release.Service | quote }}
    {{- range $labelName, $labelValue := $.Values.labels }}
    {{ $labelName | quote }}: {{ $labelValue | quote }}
    {{- end }}
  annotations:
    "helm.sh/chart": "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    {{- range $annotationName, $annotationValue := $.Values.annotations }}
    {{ $annotationName | quote }}: {{ $annotationValue | quote }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ $kind }}
    name: {{ $.Release.Name | quote }}
  minReplicas: {{ $.Values.replicas }}
  maxReplicas: {{ $.Values.autoScaling.horizontal.maxReplicas }}
  metrics:
  {{- if $.Values.autoScaling.horizontal.averageRelativeCPU }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $.Values.autoScaling.horizontal.averageRelativeCPU }}
  {{- end }}
  {{- if $.Values.autoScaling.horizontal.averageRelativeMemory }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ $.Values.autoScaling.horizontal.averageRelativeMemory }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
